name: keras
channels:
  - open3d-admin
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select
  - absl-py
  - appdirs
  - asn1crypto
  - astor
  - astroid
  - atomicwrites
  - attrs
  - automat
  - backcall
  - blas
  - bleach
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - colorama
  - constantly
  - cryptography
  - cssselect
  - cudatoolkit=9.0
  - cudnn
  - cycler
  - cython
  - cytoolz
  - dask-core
  - deap
  - decorator
  - defusedxml
  - dill
  - entrypoints
  - fastcache
  - flask
  - freetype
  - gast
  - graphviz
  - grpcio
  - h5py
  - hdf5
  - hyperlink
  - icc_rt
  - icu
  - idna
  - imagehash
  - imageio
  - incremental
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isort
  - itsdangerous
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - jupyterlab
  - jupyterlab_launcher
  - jupyterlab_server
  - keras-applications
  - keras-base
  - keras-gpu
  - keras-preprocessing
  - kiwisolver
  - lap
  - lazy-object-proxy
  - libiconv
  - libpng
  - libprotobuf
  - libsodium
  - libtiff
  - libwebp
  - libxml2
  - libxslt
  - lxml
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mccabe
  - mistune
  - mkl
  - mkl_fft
  - mkl_random
  - mock
  - more-itertools
  - mpmath
  - msys2-conda-epoch
  - nb_conda
  - nb_conda_kernels
  - nbconvert
  - nbformat
  - networkx
  - nodejs
  - notebook
  - numpy
  - numpy-base
  - olefile
  - open3d
  - opencv
  - openssl
  - pandas
  - pandoc
  - pandocfilters
  - parsel
  - parso
  - patsy
  - pbr
  - pickleshare
  - pillow
  - pip
  - pluggy
  - prometheus_client
  - prompt_toolkit
  - protobuf
  - py
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pydispatcher
  - pygments
  - pyhamcrest
  - pylint
  - pyopenssl
  - pyparsing
  - pyqt
  - pyreadline
  - pyrsistent
  - pysocks
  - pytest
  - pytest-runner
  - python
  - python-dateutil
  - python-graphviz
  - pytz
  - pywavelets
  - pywin32
  - pywinpty
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - queuelib
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - scrapy
  - seaborn
  - send2trash
  - service_identity
  - setuptools
  - sip
  - six
  - sqlite
  - statsmodels
  - stopit
  - sympy
  - tensorboard
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  - tensorflow-gpu
  - termcolor
  - terminado
  - testpath
  - tk
  - toolz
  - tornado
  - tpot
  - tqdm
  - traitlets
  - twisted
  - typed-ast
  - update_checker
  - urllib3
  - vc
  - vs2015_runtime
  - w3lib
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - widgetsnbextension
  - win_inet_pton
  - wincertstore
  - winpty
  - wrapt
  - yaml
  - zeromq
  - zlib
  - zope.interface
  - pip:
    - apptools
    - configobj
    - envisage
    - mayavi
    - open3d-python
    - primesense
    - pyface
    - traits
    - traitsui
    - vtk

